import os
import sys
import logging
from jinja2 import Template
from datetime import datetime

logger = logging.getLogger(__name__)

# Monkeypatch cffi to find macOS Homebrew dynamic libraries when running on Apple Silicon
if sys.platform == 'darwin':
    try:
        import cffi
        original_dlopen = cffi.FFI.dlopen

        def patched_dlopen(self, name, flags=0):
            try:
                return original_dlopen(self, name, flags)
            except OSError:
                if name and not name.startswith('/'):
                    # Try prepending /opt/homebrew/lib/
                    brew_path = os.path.join('/opt/homebrew/lib', name)
                    try:
                        return original_dlopen(self, brew_path, flags)
                    except OSError:
                        pass
                    
                    # Map name to common macOS Homebrew library filenames
                    base_name = name
                    if base_name.startswith('lib'):
                        base_name = base_name[3:]
                    # Remove trailing numbers like -0
                    parts = base_name.split('-')
                    if parts and parts[-1].isdigit():
                        base_name = '-'.join(parts[:-1])
                    
                    # Try standard variations
                    for ext in ['.dylib', '.0.dylib', '.so']:
                        for prefix in ['lib', '']:
                            try_name = f'{prefix}{base_name}{ext}'
                            try_path = os.path.join('/opt/homebrew/lib', try_name)
                            try:
                                return original_dlopen(self, try_path, flags)
                            except OSError:
                                pass
                raise

        cffi.FFI.dlopen = patched_dlopen
    except Exception:
        pass

try:
    from weasyprint import HTML
    WEASYPRINT_AVAILABLE = True
except Exception as e:
    WEASYPRINT_AVAILABLE = False
    WEASYPRINT_ERROR = str(e)

HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Quotation - {{ quotation.project_name }}</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Outfit:wght@400;500;600;700;800&display=swap');

        @page {
            size: A4;
            margin: 30mm 20mm 20mm 20mm;
            @top-left {
                content: "{{ quotation.creator.name if (quotation.creator and quotation.creator.name) else 'SpaceIO' }} Proposal";
                font-family: 'Outfit', sans-serif;
                font-size: 8.5pt;
                font-weight: 700;
                color: #94a3b8;
                text-transform: uppercase;
                letter-spacing: 1.5px;
                border-bottom: 1.5px solid #e2e8f0;
                padding-top: 12mm;
                padding-bottom: 6mm;
                vertical-align: middle;
            }
            @top-right {
                content: "";
                background-image: url('{{ quotation.creator.company_logo if (quotation.creator and quotation.creator.company_logo) else "http://localhost:3000/spaceio_logo.png" }}');
                background-size: auto 10mm;
                background-repeat: no-repeat;
                background-position: right center;
                border-bottom: 1.5px solid #e2e8f0;
                padding-top: 12mm;
                padding-bottom: 6mm;
                vertical-align: middle;
                width: 35mm;
            }
            @bottom-right {
                content: "Page " counter(page) " of " counter(pages) " • Generated by SpaceIO";
                font-family: 'Outfit', 'Inter', sans-serif;
                font-size: 8pt;
                color: #94a3b8;
            }
            @bottom-left {
                content: "{{ quotation.creator.name if (quotation.creator and quotation.creator.name) else 'SpaceIO' }} Proposal";
                font-family: 'Outfit', 'Inter', sans-serif;
                font-size: 8pt;
                color: #94a3b8;
            }
        }

        @page :first {
            margin: 20mm;
            @top-left {
                content: "";
                border: none;
            }
            @top-right {
                content: "";
                background-image: none;
                border: none;
            }
            @bottom-right {
                content: "";
            }
            @bottom-left {
                content: "";
            }
        }
        
        body {
            font-family: 'Inter', 'Segoe UI', Arial, sans-serif;
            color: #1e293b;
            margin: 0;
            padding: 0;
            font-size: 9.5pt;
            line-height: 1.5;
            background-color: #ffffff;
        }

        /* --- COVER PAGE --- */
        .cover-page {
            page-break-after: always;
            height: 250mm;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            padding: 15mm 0;
            box-sizing: border-box;
        }

        .cover-header {
            margin-bottom: 35mm;
        }

        .logo-container {
            display: flex;
            align-items: center;
            gap: 12px;
        }

        .logo-icon {
            display: inline-block;
            width: 38px;
            height: 38px;
            border-radius: 10px;
            background: linear-gradient(135deg, #1c1917, #b45309);
            color: white;
            font-weight: 900;
            font-size: 20px;
            line-height: 38px;
            text-align: center;
            vertical-align: middle;
        }

        .brand-text {
            display: inline-block;
            vertical-align: middle;
            margin-left: 8px;
        }

        .logo-title {
            font-family: 'Outfit', sans-serif;
            font-size: 18pt;
            font-weight: 800;
            color: #0f172a;
            letter-spacing: -0.5px;
            line-height: 1.1;
        }

        .logo-subtitle {
            font-family: 'Outfit', sans-serif;
            font-size: 7.5pt;
            color: #b45309;
            font-weight: 700;
            letter-spacing: 2px;
            text-transform: uppercase;
        }

        .cover-title-block {
            margin-bottom: auto;
            margin-top: 15mm;
        }

        .cover-badge {
            display: inline-block;
            font-family: 'Outfit', sans-serif;
            font-size: 8pt;
            font-weight: 800;
            color: #b45309;
            background-color: #fef3c7;
            padding: 5px 12px;
            border-radius: 9999px;
            letter-spacing: 1.5px;
            margin-bottom: 18px;
            text-transform: uppercase;
        }

        .cover-project-title {
            font-family: 'Outfit', sans-serif;
            font-size: 34pt;
            font-weight: 900;
            color: #0f172a;
            line-height: 1.15;
            margin: 0 0 12px 0;
            letter-spacing: -1px;
        }

        .cover-project-subtitle {
            font-size: 11.5pt;
            color: #475569;
            margin: 0;
            max-width: 85%;
            font-weight: 400;
            line-height: 1.6;
        }

        .project-details-grid {
            margin-top: auto;
            border-top: 2px solid #f1f5f9;
            padding-top: 25px;
        }

        .details-section-title {
            font-family: 'Outfit', sans-serif;
            font-size: 8.5pt;
            font-weight: 800;
            color: #94a3b8;
            letter-spacing: 2px;
            margin-bottom: 15px;
            text-transform: uppercase;
        }

        .cover-meta-table {
            width: 100%;
            border-collapse: collapse;
        }

        .cover-meta-table td {
            border: none;
            padding: 10px 25px 10px 0;
            vertical-align: top;
            width: 50%;
        }

        .grid-cell.label {
            font-family: 'Outfit', sans-serif;
            font-size: 8pt;
            font-weight: 700;
            color: #64748b;
            letter-spacing: 1.2px;
            text-transform: uppercase;
            margin-bottom: 3px;
        }

        .grid-cell.value {
            font-size: 10.5pt;
            font-weight: 600;
            color: #1e293b;
        }

        .font-bold {
            font-weight: 700 !important;
            color: #0f172a !important;
        }

        .code-font {
            font-family: 'Courier New', Courier, monospace;
            font-weight: 700 !important;
            color: #b45309 !important;
        }

        /* --- SECTION HEADERS --- */
        .section-title {
            font-family: 'Outfit', sans-serif;
            font-size: 15pt;
            font-weight: 800;
            color: #0f172a;
            margin-top: 40px;
            margin-bottom: 20px;
            border-bottom: 2px solid #f1f5f9;
            padding-bottom: 8px;
            page-break-after: avoid;
            letter-spacing: -0.3px;
        }

        .room-section {
            margin-bottom: 35px;
            page-break-inside: avoid;
        }

        .room-header {
            font-family: 'Outfit', sans-serif;
            font-size: 11.5pt;
            font-weight: 800;
            color: #1e293b;
            background-color: #f8fafc;
            border-left: 4px solid #b45309;
            padding: 8px 14px;
            margin-bottom: 15px;
            text-transform: uppercase;
            letter-spacing: 1px;
            border-radius: 0 8px 8px 0;
        }

        /* --- TABLE STYLING --- */
        table.items-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        table.items-table th {
            background-color: #f8fafc;
            color: #475569;
            font-weight: 800;
            text-align: left;
            padding: 10px 14px;
            font-size: 8.5pt;
            border-bottom: 2px solid #e2e8f0;
            text-transform: uppercase;
            letter-spacing: 0.8px;
        }

        table.items-table td {
            padding: 12px 14px;
            font-size: 9pt;
            border-bottom: 1px solid #f1f5f9;
            vertical-align: top;
            line-height: 1.4;
        }

        table.items-table tr:nth-child(even) {
            background-color: #fafbfd;
        }

        .col-item { width: 45%; }
        .col-category { width: 25%; }
        .col-qty { width: 12%; text-align: center; }
        .col-rate { width: 18%; text-align: right; }

        .text-right { text-align: right; }
        .text-center { text-align: center; }

        /* --- SUMMARY BLOCK --- */
        .summary-wrapper {
            margin-top: 30px;
            margin-bottom: 40px;
            page-break-inside: avoid;
        }

        .summary-table {
            width: 320px;
            margin-left: auto;
            margin-right: 0;
            background-color: #f8fafc;
            border-radius: 12px;
            border: 1px solid #e2e8f0;
            border-collapse: separate;
            border-spacing: 0;
            overflow: hidden;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.02);
        }

        .summary-table td {
            border: none;
            padding: 10px 16px;
            font-size: 9.5pt;
        }

        .summary-label {
            font-weight: 600;
            color: #64748b;
            text-align: left;
        }

        .summary-value {
            font-weight: 700;
            color: #1e293b;
            text-align: right;
        }

        .discount {
            color: #e11d48 !important;
        }

        .grand-total-row td {
            border-top: 1px solid #e2e8f0;
            background-color: #1c1917;
            padding: 14px 16px;
            color: #ffffff !important;
        }

        .grand-total-row td:first-child {
            border-bottom-left-radius: 11px;
        }

        .grand-total-row td:last-child {
            border-bottom-right-radius: 11px;
        }

        .grand-total-row .summary-label {
            color: #ffffff !important;
            font-weight: 800;
            font-size: 11pt;
        }

        .grand-total-row .summary-value,
        .grand-total-row .text-right {
            color: #ffffff !important;
            font-weight: 800;
            font-size: 12pt;
        }

        /* --- TERMS & SIGNATURES --- */
        .terms-section {
            margin-top: 40px;
            margin-bottom: 40px;
            page-break-inside: avoid;
            background-color: #fafbfc;
            border: 1px solid #e2e8f0;
            padding: 24px;
            border-radius: 12px;
        }

        .terms-title {
            font-family: 'Outfit', sans-serif;
            font-weight: 800;
            font-size: 10pt;
            color: #0f172a;
            margin-bottom: 12px;
            text-transform: uppercase;
            letter-spacing: 1px;
            border-bottom: 1px solid #e2e8f0;
            padding-bottom: 8px;
        }

        .terms-content {
            font-size: 8.5pt;
            color: #475569;
            line-height: 1.6;
            white-space: pre-line;
        }

        .signature-block {
            margin-top: 50px;
            page-break-inside: avoid;
            width: 100%;
        }

        .sig-table {
            width: 100%;
            border-collapse: collapse;
        }

        .sig-table td {
            border: none;
            width: 50%;
            vertical-align: top;
            padding: 0;
        }

        .sig-box {
            width: 80%;
            margin-top: 45px;
            border-top: 1px solid #cbd5e1;
            padding-top: 8px;
            text-align: center;
        }

        .sig-label {
            font-family: 'Outfit', sans-serif;
            font-size: 9pt;
            font-weight: 700;
            color: #475569;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }

        .sig-subtext {
            font-size: 7.5pt;
            color: #94a3b8;
            margin-top: 2px;
        }

        @media print {
            .no-print {
                display: none !important;
            }
        }
    </style>
</head>
<body>
    {% if weasyprint_failed %}
    <div style="background-color: #FFFBEB; border: 1px solid #F59E0B; color: #B45309; padding: 20px; margin: 20px; border-radius: 12px; font-family: 'Outfit', sans-serif; font-size: 11pt; line-height: 1.5; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);" class="no-print">
        <strong style="font-size: 13pt; color: #D97706;">⚠️ Print-Friendly Preview Mode</strong><br>
        WeasyPrint is not fully configured on this local server environment.
        You can easily save this quotation as a high-quality PDF using your browser:
        <ul style="margin: 8px 0 0 20px; padding: 0;">
            <li>Press <strong>Cmd + P</strong> (Mac) or <strong>Ctrl + P</strong> (Windows).</li>
            <li>Select <strong>Save as PDF</strong> as the Destination.</li>
            <li>Under <em>More Settings</em> / <em>Options</em>, check the <strong>Background graphics</strong> option to keep colors and layout styling.</li>
        </ul>
    </div>
    {% endif %}

    <!-- COVER PAGE -->
    <div class="cover-page">
        <div class="cover-header">
            <div style="display: flex; align-items: center; gap: 14px;">
                <img src="{{ quotation.creator.company_logo if (quotation.creator and quotation.creator.company_logo) else 'http://localhost:3000/spaceio_logo.png' }}" alt="Brand Logo" style="height: 40px; max-width: 150px; width: auto; display: inline-block; vertical-align: middle;" />
                <div class="brand-text" style="border-left: 2.5px solid #cbd5e1; padding-left: 12px; margin-left: 4px; display: inline-block; vertical-align: middle; line-height: 1.25;">
                    <span class="logo-title" style="font-family: 'Outfit', sans-serif; font-size: 16pt; font-weight: 900; color: #0f172a; letter-spacing: -0.5px; display: block; margin-bottom: 2px;">{{ quotation.creator.name if (quotation.creator and quotation.creator.name) else 'SpaceIO' }}</span>
                    <span class="logo-subtitle" style="font-family: 'Outfit', sans-serif; font-size: 7pt; color: #b45309; font-weight: 800; letter-spacing: 1.5px; text-transform: uppercase; display: block;">INTERIOR DESIGN</span>
                </div>
            </div>
        </div>
        
        <div class="cover-title-block">
            <span class="cover-badge">DESIGN PROPOSAL & ESTIMATE</span>
            <h1 class="cover-project-title">{{ quotation.project_name }}</h1>
            <p class="cover-project-subtitle">Complete interior design execution & supply estimate.</p>
        </div>
        
        <div class="project-details-grid">
            <div class="details-section-title">PROJECT & PROPOSAL METADATA</div>
            <table class="cover-meta-table">
                <tr>
                    <td class="meta-col">
                        <div class="grid-cell label">CLIENT NAME</div>
                        <div class="grid-cell value font-bold">{{ quotation.client_name }}</div>
                    </td>
                    <td class="meta-col">
                        <div class="grid-cell label">PROPOSAL DATE</div>
                        <div class="grid-cell value">{{ date_str }}</div>
                    </td>
                </tr>
                <tr>
                    <td class="meta-col">
                        <div class="grid-cell label">PROJECT NAME</div>
                        <div class="grid-cell value">{{ quotation.project_name }}</div>
                    </td>
                    <td class="meta-col">
                        <div class="grid-cell label">QUOTE VERSION</div>
                        <div class="grid-cell value font-bold">V{{ quotation.version }}</div>
                    </td>
                </tr>
                <tr>
                    <td class="meta-col">
                        <div class="grid-cell label">SITE ADDRESS</div>
                        <div class="grid-cell value">{{ quotation.site_address or 'Not Provided' }}</div>
                    </td>
                    <td class="meta-col">
                        <div class="grid-cell label">QUOTE NUMBER</div>
                        <div class="grid-cell value code-font">
                            {% if quotation.id %}
                              {% if quotation.id.startswith('local_') %}
                                LQ-{{ quotation.id[-6:] | upper }}
                              {% else %}
                                QT-{{ quotation.id[:8] | upper }}
                              {% endif %}
                            {% else %}
                              DRAFT
                            {% endif %}
                        </div>
                    </td>
                </tr>
                {% if quotation.creator %}
                <tr>
                    <td class="meta-col">
                        <div class="grid-cell label">PREPARED BY</div>
                        <div class="grid-cell value font-bold">{{ quotation.creator.name }}</div>
                    </td>
                    <td class="meta-col">
                        <div class="grid-cell label">DESIGNER CONTACT</div>
                        <div class="grid-cell value">
                            {% if quotation.creator.phone %}Phone: {{ quotation.creator.phone }}<br>{% endif %}
                            {% if quotation.creator.email %}Email: {{ quotation.creator.email }}{% endif %}
                        </div>
                    </td>
                </tr>
                {% endif %}
            </table>
        </div>
    </div>

    <!-- ROOM DETAILS -->
    <h2 class="section-title">Itemized Estimates by Room</h2>
    
    {% for room_id, room_items in rooms_grouped.items() %}
    <div class="room-section">
        <h3 class="room-header">{{ room_items[0].room_name }}</h3>
        <table class="items-table">
            <thead>
                <tr>
                    <th class="col-item">Item & Description</th>
                    <th class="col-category">Category</th>
                    <th class="col-qty text-center">Qty</th>
                    <th class="col-rate text-right">Final Rate</th>
                </tr>
            </thead>
            <tbody>
                {% for qi in room_items %}
                <tr>
                    <td class="col-item">
                        <strong>{{ qi.item_name }}</strong><br>
                        {% if qi.item_dimensions %}
                        <span style="font-size: 8pt; color: #718096;">
                            Dimensions: {{ qi.item_dimensions }}
                        </span>
                        {% endif %}
                        {% if qi.remark %}
                        <div style="font-size: 8pt; color: #b45309; margin-top: 4px; font-style: italic;">
                            Remark: {{ qi.remark }}
                        </div>
                        {% endif %}
                    </td>
                    <td class="col-category" style="font-size: 9pt; color: #4A5568; vertical-align: top;">
                        {{ qi.category_name }}
                    </td>
                    <td class="col-qty text-center" style="vertical-align: top;">
                        {{ qi.qty }} {% if qi.qty == 1 %}pc{% else %}pcs{% endif %}
                        {% if qi.pricing_type == 'sq_ft' %}
                        {% set sec_dim = qi.height if (qi.height and qi.height > 0) else (qi.breadth if (qi.breadth and qi.breadth > 0) else 1.0) %}
                        {% set area = (qi.length or 1.0) * sec_dim %}
                        <br><span style="font-size: 7.5pt; color: #64748b; white-space: nowrap; display: block; margin-top: 3px;">
                            {{ "{:g}".format(area) }} sq_ft
                        </span>
                        {% elif qi.pricing_type == 'running_ft' %}
                        <br><span style="font-size: 7.5pt; color: #64748b; white-space: nowrap; display: block; margin-top: 3px;">
                            {{ "{:g}".format(qi.length or 1.0) }} ft
                        </span>
                        {% endif %}
                    </td>
                    <td class="col-rate text-right" style="vertical-align: top;">₹{{ "{:,.2f}".format(qi.total_amount) }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endfor %}

    <!-- BILLING SUMMARY -->
    <h2 class="section-title" style="page-break-before: avoid;">Cost Summary</h2>
    <div class="summary-wrapper" style="clear: both; overflow: auto; width: 100%;">
        <table class="summary-table" style="width: 350px; margin-left: auto; margin-right: 0;">
            <tr>
                <td class="summary-label">Total Item Price:</td>
                <td class="text-right" style="color: #1e293b; font-weight: 700;">₹{{ "{:,.2f}".format(quotation.subtotal) }}</td>
            </tr>
            <tr>
                <td class="summary-label">Additional GST / Taxes:</td>
                <td class="text-right" style="color: #1e293b; font-weight: 500;">₹{{ "{:,.2f}".format(quotation.gst_amount) }}</td>
            </tr>
            {% if quotation.discount_amount > 0 %}
            <tr>
                <td class="summary-label" style="color: #E53E3E; border-top: 1px solid #e2e8f0; padding-top: 10px;">Discount Applied:</td>
                <td class="text-right" style="color: #E53E3E; border-top: 1px solid #e2e8f0; padding-top: 10px;">-₹{{ "{:,.2f}".format(quotation.discount_amount) }}</td>
            </tr>
            {% endif %}
            <tr class="grand-total-row">
                <td class="summary-label">Grand Total:</td>
                <td class="text-right">₹{{ "{:,.2f}".format(quotation.grand_total) }}</td>
            </tr>
        </table>
    </div>

    <!-- TERMS & CONDITIONS -->
    {% if quotation.terms_conditions %}
    <div class="terms-section">
        <div class="terms-title">Terms & Conditions</div>
        <div class="terms-content" style="white-space: pre-wrap;">{{ quotation.terms_conditions }}</div>
    </div>
    {% else %}
    <div class="terms-section">
        <div class="terms-title">Standard Project Terms</div>
        <div class="terms-content" style="white-space: pre-wrap;">{% if quotation.creator and quotation.creator.general_terms %}{{ quotation.creator.general_terms }}{% else %}1. Payment Terms: 40% Booking Advance, 40% on Material Delivery, 20% on Completion.
2. Prices are valid for 30 days from the proposal generation date.
3. Any extra items or alterations requested outside this proposal will be billed separately.
4. Completion timeline is subject to site handover, client design approvals, and timely payment stages.{% endif %}</div>
    </div>
    {% endif %}

    <!-- SIGNATURES -->
    <div class="signature-block">
        <table class="sig-table">
            <tr>
                <td>
                    <div class="sig-box" style="margin-left: 0; text-align: left;">
                        <div class="sig-label">Authorized Designer / Architect</div>
                        <div class="sig-subtext">For {% if quotation.creator and quotation.creator.name %}{{ quotation.creator.name }}{% else %}SpaceIO{% endif %}</div>
                    </div>
                </td>
                <td>
                    <div class="sig-box" style="margin-right: 0; margin-left: auto; text-align: right;">
                        <div class="sig-label">Client Acceptance Signature</div>
                        <div class="sig-subtext">Accepted By: {{ quotation.client_name }}</div>
                    </div>
                </td>
            </tr>
        </table>
    </div>

</body>
</html>
"""

def generate_quotation_html(quotation_dict: dict, weasyprint_failed: bool = False) -> str:
    """
    Renders the HTML quotation layout using Jinja2 templates.
    """
    # Group item entries room-wise for cleaner presentation
    rooms_grouped = {}
    total_excl_gst = 0.0
    total_item_gst = 0.0
    for qi in quotation_dict.get("items", []):
        room_id = qi["room_id"]
        if room_id not in rooms_grouped:
            rooms_grouped[room_id] = []
        rooms_grouped[room_id].append(qi)
        
        # Calculate pre-tax price and GST contribution for each item
        total_amt = qi.get("total_amount", 0.0)
        gst_percent = qi.get("snapshot_gst_percent", 0.0)
        pre_tax = total_amt / (1.0 + (gst_percent / 100.0))
        item_gst = total_amt - pre_tax
        total_excl_gst += pre_tax
        total_item_gst += item_gst
        
    date_str = datetime.now().strftime("%B %d, %Y")
    
    # Load Jinja template
    template = Template(HTML_TEMPLATE)
    html_content = template.render(
        quotation=quotation_dict,
        rooms_grouped=rooms_grouped,
        date_str=date_str,
        weasyprint_failed=weasyprint_failed,
        total_excl_gst=total_excl_gst,
        total_item_gst=total_item_gst
    )
    return html_content


def generate_quotation_pdf(quotation_dict: dict) -> bytes:
    """
    Renders an HTML quotation layout with Jinja2 and parses it into binary PDF using WeasyPrint.
    """
    if not WEASYPRINT_AVAILABLE:
        raise ImportError(
            f"WeasyPrint is not fully configured on your local system.\n"
            f"System Dependency Error: {WEASYPRINT_ERROR}\n"
            f"To enable dynamic PDF generation, please run: \n"
            f"  brew install pango\n"
            f"in your terminal and restart this server."
        )

    html_content = generate_quotation_html(quotation_dict, weasyprint_failed=False)
    
    # Render using WeasyPrint
    logger.info("Compiling PDF with WeasyPrint...")
    pdf_bytes = HTML(string=html_content).write_pdf()
    return pdf_bytes
